language: ruby
install: travis_retry ./script/bootstrap
script: ./script/cibuild
rvm:
  - 2.0.0
# whitelist
branches:
  only:
    - gh-pages
    - /(.*)/
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
