markdown: redcarpet

name: "parker's webdev resources"
author: "Parker Moore"
url: "http://webdev.parkermoo.re"
excerpt_separator: ""

permalink: /:categories/:title:output_ext

exclude:
- Rakefile
- vendor
- script
- CNAME
- README.md
- LICENSE
